name: CloudRankSystem
version: 1.0
api-version: 1.16
main: me.Sam.RankSystem.RankSystem
description: Sams rankup plugin lol
depend:
  - Vault
  - VotingPlugin
  - PlaceholderAPI
  - mcMMO
commands:
  rankup:
  rankupadmin:
  rankprefix: